version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: "dan-web-github-token" 

phases:
  install:
    commands:
      - echo "Installing Git..."
      - yum install -y git || apt-get install -y git  
      - echo "Git Login"
      - git config --global credential.helper '!f() { echo username=x-access-token; echo password=$GITHUB_TOKEN; }; f'

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo "Preparing to build Docker image..."
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t dan-web .
      - docker tag dan-web:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dan-web:latest
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/dan-web:latest
artifacts:
  files:
    - '**/*'
